/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#ifndef _GUI_H_
#define _GUI_H_

#include "gfx.h"

// Widget groups
#define GROUP_DEFAULT 0
/*
// GListeners
extern GListener gl;

// GHandles
extern GHandle ghContainerPage0;
extern GHandle ghKeyboard1;
extern GHandle ghFirst;
extern GHandle ghUser;
extern GHandle ghButton1;
extern GHandle ghContainerPage1;
extern GHandle ghContainer1;
extern GHandle ghRadiobutton3;
extern GHandle ghRadiobutton2;
extern GHandle ghRadiobutton1;
extern GHandle ghSlider1;
extern GHandle ghSlider1_1;
extern GHandle ghList1;
extern GHandle ghCheckbox2;
extern GHandle ghCheckbox1;
extern GHandle ghButton2;
extern GHandle ghLabel1;*/

// Function Prototypes
void guiCreate(void);
void guiShowPage(unsigned pageIndex);
void guiEventLoop(void);

#endif /* _GUI_H_ */

